Bug fix: add missing source files in CMakeLists.txt
Currently when building zlib with cmake, the following error is
reported.

/usr/bin/ld: libz.so.1.2.11.1-motley: undefined reference to `longest_match'
/usr/bin/ld: libz.so.1.2.11.1-motley: undefined reference to `crc_fold_init'
/usr/bin/ld: libz.so.1.2.11.1-motley: undefined reference to `crc_fold_512to32'
/usr/bin/ld: libz.so.1.2.11.1-motley: undefined reference to `slide_hash_sse'
/usr/bin/ld: libz.so.1.2.11.1-motley: undefined reference to `crc_fold_copy'
/usr/bin/ld: libz.so.1.2.11.1-motley: undefined reference to `deflate_medium'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/example64.dir/build.make:104: example64] Error 1
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/example64.dir/all] Error 2
make: *** [Makefile:160: all] Error 2

The new added source files were not added into CMakeLists.txt.

Signed-off-by: dapeng-mi <dapeng1.mi@intel.com>